import { FragmentBlogItemType } from "../../components/FragmentBlogItem/FragmentBlogItem.type";
import { ILesson, IPostLesson, IQuestion, ITypeLesson, IVideoLesson } from "../../model/Course.model";

const quizzLesson: IQuestion[] = [
    {
       id: 1,
       content: "Trong quy trình bán hàng, bước nào là quan trọng nhất để xác định nhu cầu của khách hàng?",
       answers: ["Tìm kiếm khách hàng", "Chào hàng", "Xác định nhu cầu", "Chốt đơn"],
       correctAnswerIndex: 2,
       explain: "Xác định nhu cầu giúp người bán hiểu rõ vấn đề của khách hàng và đưa ra giải pháp phù hợp.",
       imgURL: "https://example.com/question-image-1.jpg",
       index: 1
    },
    {
       id: 2,
       content: "Trong bán hàng, kỹ năng nào giúp tạo sự tin tưởng với khách hàng?",
       answers: ["Lắng nghe chủ động", "Giới thiệu sản phẩm", "Hỏi giá", "Chào tạm biệt"],
       correctAnswerIndex: 0,
       explain: "Lắng nghe chủ động giúp người bán thấu hiểu và đáp ứng nhu cầu của khách hàng một cách hiệu quả.",
       imgURL: "https://example.com/question-image-2.jpg",
       index: 2
    },
    {
       id: 3,
       content: "Yếu tố nào tạo nên một lời chào hàng hiệu quả?",
       answers: ["Giá cả rẻ", "Sản phẩm đẹp", "Lợi ích cho khách hàng", "Thời gian giao hàng nhanh"],
       correctAnswerIndex: 2,
       explain: "Một lời chào hàng hiệu quả cần nêu rõ lợi ích sản phẩm mang lại cho khách hàng.",
       imgURL: "https://example.com/question-image-3.jpg",
       index: 3
    },
    {
       id: 4,
       content: "Khi khách hàng từ chối, cách phản hồi nào giúp duy trì cơ hội bán hàng?",
       answers: ["Thuyết phục ngay lập tức", "Hỏi lý do từ chối", "Chào tạm biệt", "Bỏ qua khách hàng"],
       correctAnswerIndex: 1,
       explain: "Hỏi lý do từ chối giúp người bán hiểu rõ vấn đề và có thể đưa ra các giải pháp phù hợp.",
       imgURL: "https://example.com/question-image-4.jpg",
       index: 4
    },
    {
       id: 5,
       content: "Trong bán hàng, điều nào sau đây giúp tăng khả năng chốt đơn thành công?",
       answers: ["Giảm giá sản phẩm", "Hiểu rõ nhu cầu khách hàng", "Cung cấp thêm sản phẩm", "Liên lạc thường xuyên"],
       correctAnswerIndex: 1,
       explain: "Hiểu rõ nhu cầu của khách hàng giúp người bán có thể cung cấp sản phẩm phù hợp nhất.",
       imgURL: "https://example.com/question-image-5.jpg",
       index: 5
    }
 ];
 const videoLessons: IVideoLesson[] = [
    {
      id: 1,
      videoURL: "",
      videoId: "ZbvLJ5XtPpA",
    },
    {
      id: 2,
      videoURL: "",
      videoId: "eCsM0r3RNc4",
    },
    {
      id: 3,
      videoURL: "",
      videoId: "_uQrJ0TkZlc",
    },
    {
      id: 4,
      videoURL: "",
      videoId: "fiSFoI1oGps",
    },
    {
      id: 5,
      videoURL: "",
      videoId: "dn9cSRImmVA",
    },
  ];
  // Ví dụ dữ liệu
 const mockData: IPostLesson[] = [
   {
      id: "1",
      items: [
      {
         id: 1,
         content: "Welcome to Our Blog!",
         index: 0,
         alt: "Blog heading",
         imgURL: "",
         link: "",
         type: FragmentBlogItemType.HEADING,
      },
      {
         id: 2,
         content: "This is a simple text paragraph to introduce our content.",
         index: 1,
         alt: "",
         imgURL: "",
         link: "",
         type: FragmentBlogItemType.TEXT_SIMPLE,
      },
      {
         id: 3,
         content: "<p>This text supports <strong>HTML</strong> formatting!</p>",
         index: 2,
         alt: "",
         imgURL: "",
         link: "",
         type: FragmentBlogItemType.TEXT_EDITOR,
      },
      {
         id: 4,
         content: "_uQrJ0TkZlc",
         index: 3,
         alt: "YouTube Video",
         imgURL: "",
         link: "",
         type: FragmentBlogItemType.EMBED_YOUTUBE,
      },
      {
         id: 5,
         content: "https://www.facebook.com/plugins/post.php?href=https://www.facebook.com/20531316728/posts/10154009990506729/",
         index: 4,
         alt: "Facebook Post",
         imgURL: "",
         link: "",
         type: FragmentBlogItemType.EMBED_FACEBOOK,
      },
      {
         id: 6,
         content: "Content Image",
         index: 5,
         alt: "An example image",
         imgURL: "https://firebasestorage.googleapis.com/v0/b/stydyonline-1ace6.appspot.com/o/images%2Fcourse_9.jpg?alt=media&token=8ccc53e6-2377-4f68-9b8b-fbdc0b1c5c64",
         link: "",
         type: FragmentBlogItemType.IMAGE,
      },
   ],
   },
   {
      id: "2",
      items: [
      {
         id: 1,
         content: "Welcome to Our Blog!",
         index: 0,
         alt: "Blog heading",
         imgURL: "",
         link: "",
         type: FragmentBlogItemType.HEADING,
      },
      {
         id: 2,
         content: "This is a simple text paragraph to introduce our content.",
         index: 1,
         alt: "",
         imgURL: "",
         link: "",
         type: FragmentBlogItemType.TEXT_SIMPLE,
      },
      {
         id: 3,
         content: "<p>This text supports <strong>HTML</strong> formatting!</p>",
         index: 2,
         alt: "",
         imgURL: "",
         link: "",
         type: FragmentBlogItemType.TEXT_EDITOR,
      },
      {
         id: 4,
         content: "dn9cSRImmVA",
         index: 3,
         alt: "YouTube Video",
         imgURL: "",
         link: "",
         type: FragmentBlogItemType.EMBED_YOUTUBE,
      },
      {
         id: 5,
         content: "https://www.facebook.com/plugins/post.php?href=https://www.facebook.com/20531316728/posts/10154009990506729/",
         index: 4,
         alt: "Facebook Post",
         imgURL: "",
         link: "",
         type: FragmentBlogItemType.EMBED_FACEBOOK,
      },
      {
         id: 6,
         content: "Content Image",
         index: 5,
         alt: "An example image",
         imgURL: "https://firebasestorage.googleapis.com/v0/b/stydyonline-1ace6.appspot.com/o/images%2F4e8b618237f6eca8b5e7.jpg?alt=media&token=24f32c73-3777-4125-9583-6b2a7ff53169",
         link: "",
         type: FragmentBlogItemType.IMAGE,
      },
   ],
   },
   {
      id: "3",
      items: [
      {
         id: 1,
         content: "Welcome to Our Blog!",
         index: 0,
         alt: "Blog heading",
         imgURL: "",
         link: "",
         type: FragmentBlogItemType.HEADING,
      },
      {
         id: 2,
         content: "This is a simple text paragraph to introduce our content.",
         index: 1,
         alt: "",
         imgURL: "",
         link: "",
         type: FragmentBlogItemType.TEXT_SIMPLE,
      },
      {
         id: 3,
         content: "<p>This text supports <strong>HTML</strong> formatting!</p>",
         index: 2,
         alt: "",
         imgURL: "",
         link: "",
         type: FragmentBlogItemType.TEXT_EDITOR,
      },
      {
         id: 4,
         content: "dn9cSRImmVA",
         index: 3,
         alt: "YouTube Video",
         imgURL: "",
         link: "",
         type: FragmentBlogItemType.EMBED_YOUTUBE,
      },
      {
         id: 5,
         content: "https://www.facebook.com/plugins/post.php?href=https://www.facebook.com/20531316728/posts/10154009990506729/",
         index: 4,
         alt: "Facebook Post",
         imgURL: "",
         link: "",
         type: FragmentBlogItemType.EMBED_FACEBOOK,
      },
      {
         id: 6,
         content: "Content Image",
         index: 5,
         alt: "An example image",
         imgURL: "https://firebasestorage.googleapis.com/v0/b/stydyonline-1ace6.appspot.com/o/images%2Fcourse_8.jpg?alt=media&token=d540d658-e265-47e9-b777-91e717781aa5",
         link: "",
         type: FragmentBlogItemType.IMAGE,
      },
   ],
   },
   {
      id: "4",
      items: [
      {
         id: 1,
         content: "Welcome to Our Blog!",
         index: 0,
         alt: "Blog heading",
         imgURL: "",
         link: "",
         type: FragmentBlogItemType.HEADING,
      },
      {
         id: 2,
         content: "This is a simple text paragraph to introduce our content.",
         index: 1,
         alt: "",
         imgURL: "",
         link: "",
         type: FragmentBlogItemType.TEXT_SIMPLE,
      },
      {
         id: 3,
         content: "<p>This text supports <strong>HTML</strong> formatting!</p>",
         index: 2,
         alt: "",
         imgURL: "",
         link: "",
         type: FragmentBlogItemType.TEXT_EDITOR,
      },
      {
         id: 4,
         content: "dn9cSRImmVA",
         index: 3,
         alt: "YouTube Video",
         imgURL: "",
         link: "",
         type: FragmentBlogItemType.EMBED_YOUTUBE,
      },
      {
         id: 5,
         content: "https://www.facebook.com/plugins/post.php?href=https://www.facebook.com/20531316728/posts/10154009990506729/",
         index: 4,
         alt: "Facebook Post",
         imgURL: "",
         link: "",
         type: FragmentBlogItemType.EMBED_FACEBOOK,
      },
      {
         id: 6,
         content: "Content Image",
         index: 5,
         alt: "An example image",
         imgURL: "https://firebasestorage.googleapis.com/v0/b/stydyonline-1ace6.appspot.com/o/images%2Fcourse_10.png?alt=media&token=879d184b-b0cc-4691-bf4a-6d77ccfdc0fc",
         link: "",
         type: FragmentBlogItemType.IMAGE,
      },
   ],
   },
   {
      id: "5",
      items: [
      {
         id: 1,
         content: "Welcome to Our Blog!",
         index: 0,
         alt: "Blog heading",
         imgURL: "",
         link: "",
         type: FragmentBlogItemType.HEADING,
      },
      {
         id: 2,
         content: "This is a simple text paragraph to introduce our content.",
         index: 1,
         alt: "",
         imgURL: "",
         link: "",
         type: FragmentBlogItemType.TEXT_SIMPLE,
      },
      {
         id: 3,
         content: "<p>This text supports <strong>HTML</strong> formatting!</p>",
         index: 2,
         alt: "",
         imgURL: "",
         link: "",
         type: FragmentBlogItemType.TEXT_EDITOR,
      },
      {
         id: 4,
         content: "dn9cSRImmVA",
         index: 3,
         alt: "YouTube Video",
         imgURL: "",
         link: "",
         type: FragmentBlogItemType.EMBED_YOUTUBE,
      },
      {
         id: 5,
         content: "https://www.facebook.com/plugins/post.php?href=https://www.facebook.com/20531316728/posts/10154009990506729/",
         index: 4,
         alt: "Facebook Post",
         imgURL: "",
         link: "",
         type: FragmentBlogItemType.EMBED_FACEBOOK,
      },
      {
         id: 6,
         content: "Content Image",
         index: 5,
         alt: "An example image",
         imgURL: "https://firebasestorage.googleapis.com/v0/b/stydyonline-1ace6.appspot.com/o/images%2Fcourse_8.jpg?alt=media&token=d540d658-e265-47e9-b777-91e717781aa5",
         link: "",
         type: FragmentBlogItemType.IMAGE,
      },
   ],
   },
];
 
   
 export const lessons: ILesson[] =[
    {
       id: "1",
       type: ITypeLesson.Quiz,
       title: "Kiến thức cơ bản về bán hàng",
       description: "Bài kiểm tra kiến thức cơ bản về quy trình bán hàng và cách tạo niềm tin với khách hàng.",
       quiz: quizzLesson,
       video: null,
       index:1,
       imgUrl:"https://firebasestorage.googleapis.com/v0/b/stydyonline-1ace6.appspot.com/o/images%2Fcourse_6.png?alt=media&token=41690995-7ced-4b64-8ca9-91ca8ca416e8"
    },
    {
       id: "lesson_2",
       type: ITypeLesson.Quiz,
       title: "Kỹ năng xử lý từ chối",
       description: "Bài kiểm tra về kỹ năng phản hồi và duy trì cơ hội bán hàng khi gặp phải từ chối từ khách hàng.",
       quiz: [
          {
             id: 3,
             content: "Yếu tố nào tạo nên một lời chào hàng hiệu quả?",
             answers: ["Giá cả rẻ", "Sản phẩm đẹp", "Lợi ích cho khách hàng", "Thời gian giao hàng nhanh"],
             correctAnswerIndex: 2,
             explain: "Một lời chào hàng hiệu quả cần nêu rõ lợi ích sản phẩm mang lại cho khách hàng.",
             imgURL: "https://example.com/question-image-3.jpg",
             index: 1
          },
          {
             id: 4,
             content: "Khi khách hàng từ chối, cách phản hồi nào giúp duy trì cơ hội bán hàng?",
             answers: ["Thuyết phục ngay lập tức", "Hỏi lý do từ chối", "Chào tạm biệt", "Bỏ qua khách hàng"],
             correctAnswerIndex: 1,
             explain: "Hỏi lý do từ chối giúp người bán hiểu rõ vấn đề và có thể đưa ra các giải pháp phù hợp.",
             imgURL: "https://example.com/question-image-4.jpg",
             index: 2
          }
       ],
       video: null,
       index: 2,
       imgUrl:"https://firebasestorage.googleapis.com/v0/b/stydyonline-1ace6.appspot.com/o/images%2Fcourse_1.jpg?alt=media&token=35e3d36d-20e4-4c16-8495-ffcffa85262d"
    },
    {
       id: "3",
       type: ITypeLesson.Video,
       title: "Kỹ năng xử lý từ chối",
       description: "Video 1.",
       quiz: null,
       video: videoLessons[0],
       index: 2,
       imgUrl:"https://firebasestorage.googleapis.com/v0/b/stydyonline-1ace6.appspot.com/o/images%2Fcourse_2.jpg?alt=media&token=18b1b8d8-2854-45a0-81f2-42e8066595fe"
    },
    {
        id: "4",
        type: ITypeLesson.Video,
        title: "Kỹ năng xử lý từ chối",
        description: "Video 2.",
        quiz: null,
        video: videoLessons[1],
        index: 2,
        imgUrl:"https://firebasestorage.googleapis.com/v0/b/stydyonline-1ace6.appspot.com/o/images%2Fcourse_3.png?alt=media&token=d7c7b951-8779-4490-a603-fa651896dadf"
    },
    {
       id: "5",
       type: ITypeLesson.Post,
       title: "Post 1",
       description: "Bài kiểm tra về kỹ năng phản hồi và duy trì cơ hội bán hàng khi gặp phải từ chối từ khách hàng.",
       quiz: null,
       video: null,
       post: mockData[0],
       index: 2,
       imgUrl:"https://firebasestorage.googleapis.com/v0/b/stydyonline-1ace6.appspot.com/o/images%2Fcourse_4.jpg?alt=media&token=1f309f69-4670-48f7-bb8e-8252c4f28b28"
    },
    {
        id: "6",
        type: ITypeLesson.Post,
        title: "Post 2",
        description: "Bài kiểm tra về kỹ năng phản hồi và duy trì cơ hội bán hàng khi gặp phải từ chối từ khách hàng.",
        quiz: null,
        video: null,
        post: mockData[1],
        index: 2,
        imgUrl:"https://firebasestorage.googleapis.com/v0/b/stydyonline-1ace6.appspot.com/o/images%2Fcourse_5.jpg?alt=media&token=4d706723-7881-464e-a004-637694967d62"
     },
     {
        id: "7",
        type: ITypeLesson.Post,
        title: "Post 3",
        description: "Bài kiểm tra về kỹ năng phản hồi và duy trì cơ hội bán hàng khi gặp phải từ chối từ khách hàng.",
        quiz: null,
        video: null,
        post: mockData[2],
        index: 2,
        imgUrl:"https://firebasestorage.googleapis.com/v0/b/stydyonline-1ace6.appspot.com/o/images%2Fcourse_6.png?alt=media&token=41690995-7ced-4b64-8ca9-91ca8ca416e8"
     },
     {
        id: "8",
        type: ITypeLesson.Quiz,
        title: "Quizz 1",
        description: "Kiểm tra học sinh",
        quiz: quizzLesson,
        video: null,
        index:1,
        imgUrl:"https://firebasestorage.googleapis.com/v0/b/stydyonline-1ace6.appspot.com/o/images%2Fcourse_7.jpg?alt=media&token=964aeb26-7b5d-4e42-a111-1e0f2cbd6744"
     },
     {
      id: "9",
      type: ITypeLesson.Post,
      title: "Post 4",
      description: "Bài kiểm tra về kỹ năng phản hồi và duy trì cơ hội bán hàng khi gặp phải từ chối từ khách hàng.",
      quiz: null,
      video: null,
      post: mockData[3],
      index: 2,
      imgUrl:"https://firebasestorage.googleapis.com/v0/b/stydyonline-1ace6.appspot.com/o/images%2Fcourse_1.jpg?alt=media&token=35e3d36d-20e4-4c16-8495-ffcffa85262d"
   },
   {
      id: "10",
      type: ITypeLesson.Post,
      title: "Post 5",
      description: "Bài kiểm tra về kỹ năng phản hồi và duy trì cơ hội bán hàng khi gặp phải từ chối từ khách hàng.",
      quiz: null,
      video: null,
      post: mockData[4],
      index: 2,
      imgUrl:"https://firebasestorage.googleapis.com/v0/b/stydyonline-1ace6.appspot.com/o/images%2Fcourse_6.png?alt=media&token=41690995-7ced-4b64-8ca9-91ca8ca416e8"
   },
   {
      id: "11",
      type: ITypeLesson.Quiz,
      title: "Quizz 4",
      description: "Kiểm tra học sinh",
      quiz: quizzLesson,
      video: null,
      index:1,
      imgUrl:"https://firebasestorage.googleapis.com/v0/b/stydyonline-1ace6.appspot.com/o/images%2Fcourse_1.jpg?alt=media&token=35e3d36d-20e4-4c16-8495-ffcffa85262d"
   },
   {
      id: "12",
      type: ITypeLesson.Quiz,
      title: "Quizz 5",
      description: "Kiểm tra học sinh",
      quiz: quizzLesson,
      video: null,
      index:1,
      imgUrl:"https://firebasestorage.googleapis.com/v0/b/stydyonline-1ace6.appspot.com/o/images%2Fcourse_3.png?alt=media&token=d7c7b951-8779-4490-a603-fa651896dadf"
   },
   {
      id: "13",
      type: ITypeLesson.Video,
      title: "Kỹ năng xử lý từ chối",
      description: "Video 3",
      quiz: null,
      video: videoLessons[2],
      index: 2,
      imgUrl:"https://firebasestorage.googleapis.com/v0/b/stydyonline-1ace6.appspot.com/o/images%2Fcourse_1.jpg?alt=media&token=35e3d36d-20e4-4c16-8495-ffcffa85262d"
  },
  {
      id: "14",
      type: ITypeLesson.Video,
      title: "Kỹ năng xử lý từ chối",
      description: "Video 4",
      quiz: null,
      video: videoLessons[3],
      index: 2,
      imgUrl:"https://firebasestorage.googleapis.com/v0/b/stydyonline-1ace6.appspot.com/o/images%2Fcourse_2.jpg?alt=media&token=18b1b8d8-2854-45a0-81f2-42e8066595fe"
    },
    {
      id: "15",
      type: ITypeLesson.Video,
      title: "Kỹ năng xử lý từ chối",
      description: "Video 5",
      quiz: null,
      video: videoLessons[4],
      index: 2,
      imgUrl:"https://firebasestorage.googleapis.com/v0/b/stydyonline-1ace6.appspot.com/o/images%2Fcourse_5.jpg?alt=media&token=4d706723-7881-464e-a004-637694967d62"
  },
 
 ]